### PR TITLE
fix(websocket): add headers.authentication in connection params

### PR DESCRIPTION
**Pull request by thetre97**
Add correct headers key to support authentication header

### CODE REVIEW

**Comment by thetre97** [comment]
#134 https://github.com/Akryum/vue-apollo/issues/520

**Comment by dohomi** [comment]
@Akryum this would be great if you could merge it. I debugged for quite a while the issue till I found that there is a mismatch between how wsEndpoint and httpEndpoint are being set

**Comment by sanconley** [comment]
When is this going to be merged in?

**Comment by oscar6echo** [comment]
@Akryum Could you please merge this PR.  
It's tiny but without it users cannot use subscriptions with [Hasura](https://docs.hasura.io/1.0/graphql/manual/subscriptions/index.html#communication-protocol).

**Comment by oscar6echo** [comment]
@Akryum thx a lot for your swift merge/release 👍 

You were so fast it seems you misspelled the new release 0.12.1 instead of (probably ?) 0.21.1 😄  
I can't see any impact though.

**Pull request merged**
